BZlab/urls.py
from django.urls import path
from django.conf.urls import url
from django.contrib import admin
from inventory.views import HomeView, Login, Logout, AddUser, ChangeUserDataView, AddSupplier, UpdateSupplier, \
    DeleteSupplier, ViewSuppliers, ViewSamples, ViewRecipes, AddSample, DeleteSample, UpdateSample

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name='home_view'),
    url(r'^login', Login.as_view(), name='login-form'),
    url(r'^logout', Logout.as_view(), name='logout'),
    url(r'^add_user', AddUser.as_view(), name='add-user'),
    path('edit_user/<user_id>', ChangeUserDataView.as_view(), name='edit-user'),
    url(r'^add_supplier', AddSupplier.as_view(), name='add-supplier'),
    path('update_supplier/<pk>', UpdateSupplier.as_view(), name='update-supplier'),
    path('delete_supplier/<pk>', DeleteSupplier.as_view(), name='delete-supplier'),
    url(r'^view_suppliers/', ViewSuppliers.as_view(), name='view-suppliers'),

    path('samples_list/', ViewSamples.as_view(), name='samples-view'),
    path('recipes/', ViewRecipes.as_view(), name='recipes-view'),
    url(r'^add_sample/', AddSample.as_view(), name='add-sample'),
    path('delete_sample/<pk>', DeleteSample.as_view(), name='delete-sample'),
    path('update_sample/<pk>', UpdateSample.as_view(), name='update-sample'),

]

"""
url(r'^product/(?P<id>([0-9]+))/$', ProductView.as_view(), name='product'),
"""

inventory/models.py
from django.db import models
from datetime import date
from django.contrib.auth.models import User

# Create your models here.

DOCUMENTS = ((False, 'Nie'),
             (True, 'Tak')
            )

ROOMS = (('1', 'pokój nr 1'),
         ('2', 'pokój nr 2'),
         ('3', 'pokój nr 3'),
         ('4', 'pokój nr 4'),
         ('5', 'pokój nr 5'),
         ('6', 'pokój nr 6'),
         ('7', 'pokój nr 7'),
         ('8', 'pokój nr 8'),
)





class Supplier(models.Model):
    name = models.CharField(max_length=500, unique=True)
    address = models.CharField(max_length=500)
    email = models.EmailField(max_length=254)
    telephone = models.CharField(max_length=50)
    contact_person = models.CharField(max_length=128)

    def __str__(self):
        return self.name

class Sample(models.Model):

    sample_code = models.CharField(max_length=128, unique=True, verbose_name='kod próbki')
    name = models.CharField(max_length=500, verbose_name='nazwa')
    supplier = models.ForeignKey(Supplier, on_delete=models.CASCADE, verbose_name='dostawca')
    amount = models.IntegerField(verbose_name='ilość opakowań')
    mass = models.DecimalField(decimal_places=1, max_digits=4, verbose_name='masa próbki w kg')
    MSDS = models.BooleanField(choices=DOCUMENTS, verbose_name='dołączony MSDS?')
    TDS = models.BooleanField(choices=DOCUMENTS, verbose_name='dołączony TDS?')
    location = models.CharField(choices=ROOMS, max_length=50, verbose_name='miejsce składowania')
    date_received = models.DateField(default=date.today, verbose_name='data przyjęcia')
    user = models.ForeignKey(User, on_delete=models.SET('deleted user'), verbose_name='podpis')


    def __str__(self):
        return self.name

inventory/forms.py
from django import forms
from django.contrib.auth.models import User

#from .validators import validate_name, validate_surname, validate_email_domain
from inventory.models import Supplier, Sample, DOCUMENTS, ROOMS


class UserForm(forms.Form):
    first_name = forms.CharField(label='Imię', max_length=128)
    last_name = forms.CharField(label='Nazwisko', max_length=128)
    email = forms.EmailField(label='Email')



class LoginForm(forms.Form):
    username = forms.CharField(max_length=128)
    password = forms.CharField(max_length=128, widget=forms.PasswordInput)


class AddUserForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')

    username = forms.CharField(max_length=128)
    password = forms.CharField(max_length=128, widget=forms.PasswordInput)
    repeat_password = forms.CharField(max_length=128, widget=forms.PasswordInput)



class ChangeUserDataForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')

    username = forms.CharField(max_length=128)
    password = forms.CharField(max_length=128, widget=forms.PasswordInput)
    repeat_password = forms.CharField(max_length=128, widget=forms.PasswordInput)


class SupplierForm(forms.ModelForm):
    class Meta:
        model = Supplier
        fields = '__all__'



class UpdateSampleForm(forms.ModelForm):
    class Meta:
        model = Sample
        fields = '__all__'
        exclude = ['sample_code', 'user']


"""    
    sample_code = forms.CharField(max_length=128, verbose_name='kod próbki')
    name = forms.CharField(max_length=500, verbose_name='nazwa')
    supplier = forms.ForeignKey(Supplier, on_delete=models.CASCADE, verbose_name='dostawca')
    amount = forms.IntegerField(verbose_name='ilość opakowań')
    mass = forms.DecimalField(decimal_places=1, max_digits=4, verbose_name='masa próbki w kg')
    MSDS = forms.BooleanField(choices=DOCUMENTS, verbose_name='dołączony MSDS?')
    TDS = forms.BooleanField(choices=DOCUMENTS, verbose_name='dołączony TDS?')
    location = forms.CharField(choices=ROOMS, max_length=50, verbose_name='miejsce składowania')
    date_received = forms.DateField(default=date.today, verbose_name='data przyjęcia')
"""

class AddSampleForm(forms.ModelForm):
    class Meta:
        model = Sample
        fields = '__all__'
        exclude = ['sample_code', 'user']

class SearchForm(forms.Form):
    search_term = forms.CharField(label='', max_length=200)


"""
    password = forms.CharField(label='password', widget=forms.PasswordInput)
    re_password = forms.CharField(label='confirm password', widget=forms.PasswordInput)

"""

inventory/views.py
from django.shortcuts import render
from django.views import View
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.views import View

from inventory.models import Supplier, Sample
from .forms import LoginForm, AddUserForm, ChangeUserDataForm, AddSampleForm, UpdateSampleForm, SearchForm
from django.views.generic import DeleteView, CreateView, UpdateView
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.forms.models import model_to_dict
import re
import os
from barcode import generate
import datetime
# Create your views here.


class HomeView(View):
    def get(self, request):

        return render(request, 'home.html')

    def post(self, request):

        return HttpResponse('post request')



class Login(View):

    def get(self, request):
        form = LoginForm()
        return render(request, 'login.html', {'form':form})

    def post(self, request):
        form = LoginForm(request.POST)
        if form.is_valid():
            userAuth = authenticate(**form.cleaned_data)

            if userAuth:
                login(request, userAuth)
                logged_in = request.user.is_authenticated

                return redirect('/')
                    #render(request, 'home.html', {'data':userAuth})
            else: return render(request, 'login.html', {'form':form,
                                                        'message':'wrong data'})

class Logout(View):


    def get(self, request):
        logout(request)
        form = LoginForm()
        return render(request, 'login.html', {'form':form})


    def post(self, request):
        logout(request)
        form = LoginForm()
        return render(request, 'login.html', {'form':form})


class AddUser(View):

    def get(self, request):

        form = AddUserForm()
        return render(request, 'add_user.html', {'form':form})

    def post(self, request):

        form = AddUserForm(request.POST)
        if form.is_valid():

            try:
                User.objects.get(username=form.cleaned_data['username'])

                return render(request, 'add_user.html', {'form': form,
                                                         'message': 'user already exists'})

            except Exception as e:
                if form.cleaned_data['password'] == form.cleaned_data['repeat_password']:

                    User.objects.create_user(username=form.cleaned_data['username'],
                                             password=form.cleaned_data['password'],
                                             first_name=form.cleaned_data['first_name'],
                                             last_name=form.cleaned_data['last_name'],
                                             email=form.cleaned_data['email'])


                    return redirect('/')

                else:
                    return render(request, 'add_user.html', {'form': form,
                                                             'message': 'passowords are not the same'})
        return render(request, 'add_user.html', {'form': form,
                                                 'message': 'coś nie tak w formularzu'})



class ChangeUserDataView(View):

    def get(self, request, user_id):


        try:
            user = User.objects.get(pk=user_id)
        except:
            return HttpResponse('there is no user with id {}'.format(user_id))

        form = ChangeUserDataForm(initial=model_to_dict(user))
        print(request.user.username)

        return render(request, 'change_user_data.html', {'form': form,
                                                        'user_id': user_id})

    def post(self, request, user_id):
        form = ChangeUserDataForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            print(data)
            user = User.objects.get(pk=user_id)
            if data['password'] == data['repeat_password']:
                user.set_password(data['password'])
                user.username = (data['username'])
                user.save()


                return redirect('/')
            else:
                return render(request, 'change_user_data.html', {'form': form,
                                                                'error': 'password not the same',
                                                                'user_id': user_id
                                                                 })
        return render(request, 'change_user_data.html', {'form': form,
                                                        'error': 'form not valid',
                                                        'user_id': user_id
                                                         })




class AddSupplier(CreateView):
    model = Supplier
    fields = '__all__'
    success_url = '/'


class UpdateSupplier(UpdateView):
    model = Supplier
    fields = '__all__'
    template_name_suffix = '_update_form'
    success_url = '/'


class ViewSuppliers(View):
    def get(self, request):
        suppliers = Supplier.objects.all()

        return render(request, 'supplier_list.html', {'suppliers':suppliers})


class DeleteSupplier(DeleteView):
    model = Supplier
    success_url = '/'




class AddSample(View):
    def get(self, request):
        form = AddSampleForm()

        return render(request, 'add_sample.html', {'form': form} )

    def post(self, request):

        form = AddSampleForm(request.POST)
        if form.is_valid():
            print(form.cleaned_data)

            number_of_samples_that_day = Sample.objects.filter(date_received=form.cleaned_data['date_received']).count()

            sample_code = '{}-{}'.format(form.cleaned_data['date_received'],number_of_samples_that_day+1)
            
            data = form.cleaned_data
            data['sample_code'] = sample_code
            data['user'] = request.user
            data['user_id'] = request.user.pk


            try:
                new_sample = Sample.objects.create(**data)

                return redirect('/samples_list')
            except Exception as e:
                return render(request, 'add_sample.html', {'form': form,
                                                 'message': e})



        return render(request, 'add_sample.html', {'form': form,
                                                 'message': 'coś nie tak w formularzu'})

class UpdateSample(UpdateView):

    fields = ['name', 'supplier', 'amount', 'mass', 'MSDS', 'TDS', 'location', 'date_received' ]

    fields = ['name', 'supplier', 'amount', 'mass', 'MSDS', 'TDS', 'location', 'date_received']


    template_name_suffix = '_update_form'
    success_url = '/samples_list'


class DeleteSample(DeleteView):
    model = Sample
    success_url = '/samples_list'





class ViewSamples(View):

    def get(self, request):
        form = SearchForm()
        samples = Sample.objects.all().order_by('-date_received')


        return render(request, 'samples_list.html', {'samples': samples,
                                                     "form": form})

    def post(self, request):
        form = SearchForm(request.POST)
        if form.is_valid():
            try:
                data = form.cleaned_data['search_term']

                # żeby można było wpisać kilka słów i oddzielić dowolnym znakiem

                word_list = re.sub("[^\w]", " ", data).split()
                result = Sample.objects.filter(name__icontains=word_list[0])
                for data in word_list:
                    result_sample_code = Sample.objects.filter(sample_code__icontains=data)
                    result_name = Sample.objects.filter(name__icontains=data)
                    result_supplier = Sample.objects.filter(supplier__name__icontains=data)
                    result_amount = Sample.objects.filter(amount__icontains=data)
                    result_mass = Sample.objects.filter(mass__icontains=data)
                    result_location = Sample.objects.filter(location__icontains=data)
                    result_date_received = Sample.objects.filter(date_received__icontains=data)
                    result_user = Sample.objects.filter(user__username__icontains=data)

                    result_loop = result_sample_code | \
                                  result_name | \
                                  result_supplier | \
                                  result_amount | \
                                  result_mass | \
                                  result_location | \
                                  result_date_received | \
                                  result_user
                    result = result | result_loop

                message = f'wyniki wyszukiwania dla: {", ".join(word_list)}'
                return render(request, 'samples_list.html', {'samples': result,
                                                               'message': message,
                                                               'form': form})

            except Exception as e:
                return HttpResponse(e)
        return HttpResponse('form not valid')




class ViewRecipes(View):
    def get(self, request):

        return HttpResponse('get')

inventory/templates/add_sample.html
{% extends "home.html" %}
{% load crispy_forms_tags %}
{% block content_logged_in %}


    <form method="post" enctype="multipart/form-data" class="form text-center"> {% csrf_token %}
        {{form.as_p}}
        <input type="submit" class="btn btn-lg btn-primary " value="Zapisz" />

    </form>
{{ message }}
{% endblock %}

inventory/templates/add_user.html
{% extends "home.html" %}

{% block content_logged_out %}
<div class="text-center">
        <h3>Dodawanie użytkownika

        </h3>



        <form action="{%url 'add-user' %}" method="post" class="form" >
        {% csrf_token %}
        {{form.as_ul}}
                <input type="submit" class="btn btn-lg btn-primary" value="Wduś guzik!">
        </form>

<br><hr><br>
{{message}}

</div>
{% endblock %}

inventory/templates/barcode.html
{% extends "home.html" %}

{% load static %}
{% block content_logged_in %}

        <h2 class="text-center">Naklejka dla próbki: {{ file.name }}</h2>


<div class="container text-center">
<div >
        <img src="{% static file.barcode.url %}" class=" img-fluid max-width: 100%">
 <br>
    {{ message }}
    </div>
{{file.barcode.url}}

</div>
<div class="text-center">
    <a href="{% url 'samples-view' %}">Lista próbek</a>
    </div>
{% endblock %}

inventory/templates/change_user_data.html
{% extends "home.html" %}


{% block content_logged_in %}
<div class="text-center">
<h2>Change password</h2>



        <form action="{% url 'edit-user' user_id %}" method="post" class="form">
         {% csrf_token %}
        {{form.as_ul}}

        <input type="submit" value="Wduś guzik!" class="btn-primary btn">

        </form>


            <br>
            {{error}}

</div>
{% endblock %}

inventory/templates/home.html
<!doctype html>

<html>
    <head><meta charset="utf-8">


    {% load static %}
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'css/styles.css' %}">
        <link rel="script" href="{% static 'js/script.js' %}">


    <title>BZ chemical inventory</title>

<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    </head>
    <body>




    <div class="row">
        <div class="col text-right">

            {% if logged_in  %}

                Zalogowany jako: {{data}}
                <a href="{% url 'logout' %}">Wyloguj</a>
                <a href="{% url 'edit-user' data.id %}">Zmień dane</a>
            {% else %}
                <a href="{% url 'login-form' %}">Zaloguj</a>
                <a href="{% url 'add-user' %}">Zarejestruj</a>
            {% endif %}

        </div>

    </div>

    <div class="row">
    <div class="col text-center">
    {% block title %}
        <h1>Rejestr próbek przychodzących</h1>

        <br>
    {% endblock %}
    </div>
    </div>



    {% if logged_in  %}

    {% block content_logged_in %}

    <div class="row text-center" >
        <div class="col main-menu text-center">
<p>
                <a class="btn btn-lg btn-primary" href="{% url 'samples-view' %}" >Lista próbek</a>
    </p>
            <p>
            <a class="btn btn-lg btn-primary" href="{% url 'view-suppliers' %}">Lista dostawców</a>
            </p>

    </div>
    </div>



    {% endblock %}


    {% else %}

        {% block content_logged_out %}
        <p class="text-center">
            Incoming samples log
            <br>
            Please log in to continue
        </p>
        {% endblock %}
    {% endif %}


<div class="row">
<div class="col text-center">
    <br><a href="/">Home</a>
</div>
</div>


    <footer>


    </footer>




    </body>
</html>

inventory/templates/login.html
{% extends "home.html" %}


{% block content_logged_out %}

<h2 class="text-dark text-center">Login</h2>
<ul>

    {% if form %}
        <form action="{%url 'login-form' %}" method="post" class="form-signin text-center">
         {% csrf_token %}
        {{form.as_ul}}

        <input type="submit" class="" value="Wduś guzik!">


{% endif %}

            <br>
            {{message}}
</ul>

{% endblock %}

inventory/templates/sample_photo.html
{% extends "home.html" %}

{% load static %}
{% block content_logged_in %}

        <h2 class="text-center">Zdjęcie próbki nr: {{ file.sample_code }}</h2>


<div class="container-fluid text-center">
<div >

    <img src="{% static file.photo.url %}" class=" img-fluid max-width: 100%">
    <br>
    {{ message }}

    </div>
{{file.photo.url}}
    </div>
<div class="text-center container-fluid">
    <a href="{% url 'samples-view' %}">Lista próbek</a>
    </div>
{% endblock %}

inventory/templates/sample_update_form.html
{% extends "home.html" %}


{% block content_logged_in %}

<h2>Edycja próbki</h2>



        <form method="post" enctype="multipart/form-data" class="form text-center" action="{% url 'update-sample' pk %}">
         {% csrf_token %}
        {{form.as_ul}}

        <input type="submit" class="btn btn-lg btn-primary btn-block" value="Zapisz zmiany">

        </form>


            <br>
            {{error}}


{% endblock %}

inventory/templates/samples_list.html
{% extends "home.html" %}


{% block content_logged_in %}

        <h2 class="text-center">Próbki</h2>

    <div class="search-label-icon text-center">
    <form method="post" enctype="multipart/form-data">
         {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Szukaj">

        </form>

    {{ message }}
    </div>
    <br>

<div class="container text-center">
<div class="col text-center">
        <table class="col table-responsive-sm table-hover table-bordered text-center table-striped">
            <thead class="thead-dark">
            <tr class="thead-dark">

                <th>Kod próbki</th>
                <th>Nazwa</th>
                <th>Dostawca</th>
                <th>Ilość</th>
                <th>Masa [kg]</th>
                <th>MSDS</th>
                <th>TDS</th>
                <th>Miejsce składowania</th>
                <th>Data przyjęcia</th>
                <th>Przyjmujący</th>

                <th>Opcje</th>

                

            </tr>


            </thead>

                {% for sample in samples %}
                <tr>
                    <td>{{sample.sample_code}}</td>
                    <td>
                        <a href="/update_sample/{{sample.id}}">{{sample.name}}</a>
                    </td>
                    <td>{{sample.supplier.name}}</td>
                    <td>{{sample.amount}}</td>
                    <td>{{sample.mass}}</td>
                    <td>{{sample.get_MSDS_display}}</td>
                    <td>{{sample.get_TDS_display}}</td>
                    <td>{{sample.get_location_display}}</td>
                    <td>{{sample.date_received}}</td>
                    <td>{{sample.user}}</td>
                    

                    <td><a href="/delete_sample/{{sample.id}}">Usuń próbkę</a></td>
                </tr>
                {% endfor %}
        </table>
    </div>
<a href="{% url 'add-sample' %}">Dodaj próbkę</a>
    </div>

{% endblock %}

inventory/templates/supplier_list.html
{% extends "home.html" %}

{% block content_logged_in %}
<div class="container-fluid text-center">

        <h2>Dostawcy</h2>

        <table class="col table-responsive-sm table-hover table-bordered text-center table-striped">
            <tr>

                <th>Nazwa</th>
                <th>Adres</th>
                <th>Osoba kontaktowa</th>
                <th>Email</th>
                <th>Telefon</th>




            </tr>
                {% for supplier in suppliers %}
                <tr>
                    <td>

                        <a href="/update_supplier/{{supplier.id}}">{{supplier.name}}</a>

                    </td>
                    <td>{{supplier.address}}</td>
                    <td>{{supplier.contact_person}}</td>
                    <td>{{supplier.email}}</td>
                    <td>{{supplier.telephone}}</td>


                    <td><a href="/delete_supplier/{{supplier.id}}">Usuń dostawcę</a></td>
                </tr>
                {% endfor %}
        </table>

<br><a href="{% url 'add-supplier' %}">Dodaj dostawcę</a>

</div>

{% endblock %}